typography_spectrum: 0.09284167271107435
content_rating:
  adult: true
color:
  brandStrength: 0.8473780076019466
  lightness: 0.04051936836913228
  saturation: 0.6660259363707155
  rhythmicContrast: 0.27286777016706765
  brandColors:
    - '#E2E2E2'
    - '#75766D'
    - '#B0AFA9'
    - '#373536'
    - '#201E19'
layout_spectrum: 0.1520360156428069
author:
  name: Samuel
  email: samuelsharpe001@yahoo.com
  url: jeffcollet.com
name: Origami Llama
title: Upon Media
